# Generated by Django 4.1.9 on 2023-11-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDeDatos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tabla',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('basesDeDatos', models.ManyToManyField(blank=True, to='core.basededatos')),
                ('clasificaciones', models.ManyToManyField(blank=True, to='core.clasificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Visualizacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('clasificaciones', models.ManyToManyField(blank=True, to='core.clasificacion')),
                ('tablasDeEntrada', models.ManyToManyField(blank=True, to='core.tabla')),
            ],
        ),
        migrations.CreateModel(
            name='Termino',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('definicion', models.TextField(blank=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('clasificaciones', models.ManyToManyField(blank=True, to='core.clasificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('clasificaciones', models.ManyToManyField(blank=True, to='core.clasificacion')),
                ('tablasDeEntrada', models.ManyToManyField(blank=True, related_name='tablas_entrada', to='core.tabla')),
                ('tablasDeSalida', models.ManyToManyField(blank=True, related_name='tablas_salida', to='core.tabla')),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('definicion', models.TextField(blank=True)),
                ('medida', models.TextField(blank=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('clasificaciones', models.ManyToManyField(blank=True, to='core.clasificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Columna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('clasificaciones', models.ManyToManyField(blank=True, to='core.clasificacion')),
                ('tablas', models.ManyToManyField(blank=True, to='core.tabla')),
            ],
        ),
        migrations.AddField(
            model_name='basededatos',
            name='clasificaciones',
            field=models.ManyToManyField(blank=True, to='core.clasificacion'),
        ),
    ]
